set_property SRC_FILE_INFO {cfile:d:/fpga/Embedded_Vitis/ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc rfile:../ps_pl_bram.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:system_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/fpga/Embedded_Vitis/ps_pl_bram/ps_pl_bram.srcs/constrs_1/new/system_wrapper.xdc rfile:../ps_pl_bram.srcs/constrs_1/new/system_wrapper.xdc id:2} [current_design]
current_instance system_i/processing_system7_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.6
current_instance
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/blk_mem_gen_0/U0/doutb[0]} {system_i/blk_mem_gen_0/U0/doutb[1]} {system_i/blk_mem_gen_0/U0/doutb[2]} {system_i/blk_mem_gen_0/U0/doutb[3]} {system_i/blk_mem_gen_0/U0/doutb[4]} {system_i/blk_mem_gen_0/U0/doutb[5]} {system_i/blk_mem_gen_0/U0/doutb[6]} {system_i/blk_mem_gen_0/U0/doutb[7]} {system_i/blk_mem_gen_0/U0/doutb[8]} {system_i/blk_mem_gen_0/U0/doutb[9]} {system_i/blk_mem_gen_0/U0/doutb[10]} {system_i/blk_mem_gen_0/U0/doutb[11]} {system_i/blk_mem_gen_0/U0/doutb[12]} {system_i/blk_mem_gen_0/U0/doutb[13]} {system_i/blk_mem_gen_0/U0/doutb[14]} {system_i/blk_mem_gen_0/U0/doutb[15]} {system_i/blk_mem_gen_0/U0/doutb[16]} {system_i/blk_mem_gen_0/U0/doutb[17]} {system_i/blk_mem_gen_0/U0/doutb[18]} {system_i/blk_mem_gen_0/U0/doutb[19]} {system_i/blk_mem_gen_0/U0/doutb[20]} {system_i/blk_mem_gen_0/U0/doutb[21]} {system_i/blk_mem_gen_0/U0/doutb[22]} {system_i/blk_mem_gen_0/U0/doutb[23]} {system_i/blk_mem_gen_0/U0/doutb[24]} {system_i/blk_mem_gen_0/U0/doutb[25]} {system_i/blk_mem_gen_0/U0/doutb[26]} {system_i/blk_mem_gen_0/U0/doutb[27]} {system_i/blk_mem_gen_0/U0/doutb[28]} {system_i/blk_mem_gen_0/U0/doutb[29]} {system_i/blk_mem_gen_0/U0/doutb[30]} {system_i/blk_mem_gen_0/U0/doutb[31]}]]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/blk_mem_gen_0/U0/addrb[2]} {system_i/blk_mem_gen_0/U0/addrb[3]} {system_i/blk_mem_gen_0/U0/addrb[4]} {system_i/blk_mem_gen_0/U0/addrb[5]} {system_i/blk_mem_gen_0/U0/addrb[6]} {system_i/blk_mem_gen_0/U0/addrb[7]} {system_i/blk_mem_gen_0/U0/addrb[8]} {system_i/blk_mem_gen_0/U0/addrb[9]} {system_i/blk_mem_gen_0/U0/addrb[10]} {system_i/blk_mem_gen_0/U0/addrb[11]} {system_i/blk_mem_gen_0/U0/addrb[12]}]]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list system_i/blk_mem_gen_0/U0/enb]]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
